### ISSUE TITLE
cures, heals +8 not changing to megacures

### ISSUE THREAD

**Issue by stevecotton** [stevecotton/SXCollection#9]
Some units have cures,heals +8 but don't get upgraded to megacures, and it seems nothing upgrades to minorcures. IIRC there are also units with cures, heals +12.

The first task is collecting the list of affected units.

megacures: AE_mag_Prophet_of_Light
minorcures: AE_mrc_tribe_Voodoo_Doctor
minor-regen: AE_stf_minotaurs_Overlord

**Comment by Jordy-Jordan** [comment]
There's a way to list them from wesnoth.
In unit Description of any unit,scroll to bottom then U would see abilities, weapon specs,factions....
Click on abilities and then choose "cure,heals +8".
Or easier way, choose an unit with "cure,heals +8" and just click on "cure,heals +8" in his description as a pro :+1:

**Comment by stevecotton** [comment]
Thanks, but that also includes unaffected units like the Elvish Shyde. I think I've found the fix, now in commit 6e9ca19526b17e07127d4b9c397033a54b309168
